[package]
name = "storage"
version = "0.1.0"
edition = "2024"

[lib]
name = "storage"
path = "src/lib.rs"

[dependencies]
sea-orm = { version = "*", features = ["runtime-tokio-native-tls", "with-uuid", "mock", "sqlx-postgres"] }
chrono = { version = "*", features = ["serde"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
bcrypt = "*"
jsonwebtoken = { version = "*", features = ["rust_crypto"] }
uuid = { version = "*", features = ["v4", "serde"] }
anyhow = "*"
thiserror = "*"
tracing = "*"
